### ISSUE TITLE
AdaptiveCardExtension manifest supportedHosts should contain SharePointWebPart

### ISSUE THREAD

**Issue by ms-nichoi** [microsoft/Viva-Connections-Extensibility-Beta#1]
The scaffolded ACE manifest will contain this line:

`  "supportedHosts": ["Dashboard", "SharePointWebPart"],
`

**Please do not modify this array.**

(Removing "SharePointWebPart" will prevent the ACE from being added to the Workbench or the Dashboard page.)

**Comment by johnguy0** [comment]
Resolved with SPFx 1.13.0
