### ISSUE TITLE
QuickViews should be able to fetch data on demand

### ISSUE THREAD

**Issue by vman** [microsoft/Viva-Connections-Extensibility-Beta#16]
#### Versions
[Windows 10]  Operating System
[v12.22.1]  Node version
[4.0.2]  Gulp version
[1.13.0-beta.5]  SPFx Generator version (`npm list -g @microsoft/generator-sharepoint`)

#### Expected or Desired Behavior
[Continuing on from this discussion in Teams](https://teams.microsoft.com/l/message/19:1a26e350cce84d0984699f61e7060f8b@thread.tacv2/1621578151263?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=18f1b199-63c3-4547-abe1-04f46ee8b40a&parentMessageId=1620896450296&teamName=Viva%20Connections%20Preview&channelName=%F0%9F%92%AD%20Discussions&createdTime=1621578151263) 

QuickViews should be able to fetch data on demand with Promises instead on data having to be passed down to them from the ACE. 

#### Observed Behavior
Currently only the `BaseAdaptiveCardExtension` class contains and OnInit method which returns a Promise and can be used to fetch data asynchronously. 

This effectively translates to getting all the data on first load instead of fetching it on demand when the user invokes the QuickView. If there are a large number of ACEs on the dashboard then all of them are going to eagerly load all the data also for the QuickViews even if the user never invokes the quick view.

**Comment by anoopt** [comment]
@vman - In a recent demo Patrick Rodgers showed how to get the content of a news article on demand in a quickview. Is that related to/answer your question?

[Link to the code](https://github.com/pnp/spfx-reference-scenarios/blob/main/samples/CompanyNewsCard-SPListData/src/adaptiveCardExtensions/companyNews/quickView/QuickView.ts#L46) 

[The related part of the demo](https://youtu.be/RvDsmZJ95xM?t=2167)

**Comment by vman** [comment]
Thanks @anoopt! That is certainly a workaround to make async calls in a Quick View. However, if there was an OnInit method for the quick view as well, it would make things a lot easier.
