### ISSUE TITLE
Small updates to lab 3 instructions

### ISSUE THREAD

**Issue by jansenbe** [microsoft/Viva-Connections-Extensibility-Beta#17]
Following code snippets should be added to the lab 3 instructions to be complete:

**HelloWorldAdaptiveCardExtension.ts**
`import { DetailedView } from './quickView/DetailedQuickView';`
`private _cardIndex: number;`

**QuickView.ts**
The instructions show: 

import { DETAILED_QUICK_VIEW_REGISTRY_ID } from '../HelloWorldAdaptiveCardExtension`;

Note the backtick versus the single quote.

Overall just some small changes, but might help folks who are completely new to SPFx and TypeScript

**Comment by tinsheep** [comment]
I feel like the import { DetailedView } from './quickView/DetailedQuickView'; should be in Step 2 instead of step 4 because you need it before the reload the workbench to do the test in Step 3 no?
