### ISSUE TITLE
When data loading in `onInit` takes too much time the card is not shown anymore

### ISSUE THREAD

**Issue by jansenbe** [microsoft/Viva-Connections-Extensibility-Beta#20]
#### Versions
[ Win10 ] Operating System
[ v14.17.0 ] Node version
[ 4.0.2 ] Gulp version
[ 1.13.0-beta 5 ] SPFx Generator version (npm list -g @microsoft/generator-sharepoint)

#### Expected or Desired Behavior

Data loading in `onInit` is a common use case and when data loading is slower than expected the card should still load. 

#### Observed Behavior

When I'm calling an Azure Function from `onInit` the initial call to the function might take a few seconds longer as it's warming up...when that happens the net result is that the card is not shown at all in the dashboard.

#### Steps to Reproduce

Do something in `onInit` that prevents the promise from resolving within about 5 seconds (didn't time this) and your card will not be shown.

**Comment by johnguy0** [comment]
This should be resolved. If this is still repro-ing, please open an issue on [GA issue list.](https://github.com/SharePoint/sp-dev-docs/issues)
