### ISSUE TITLE
[QuickView]: [Videos Not playing]

### ISSUE THREAD

**Issue by ThomasJKlug** [microsoft/Viva-Connections-Extensibility-Beta#21]
#### Versions
[  Big Sur  ]  Operating System
[  12.13.0  ]  Node version
[  CLI version: 2.3.0 ]
[ Local version: 4.0.2 ]  Gulp version
[  @microsoft/generator-sharepoint@1.13.0-beta.5  ]  SPFx Generator version
#### Expected or Desired Behavior
Videos to play in Quick View

#### Observed Behavior
Video closes with an unhandled promise rejection after load.

https://user-images.githubusercontent.com/83296371/122974342-cffcd180-d357-11eb-91f6-149d3bcb59b2.mov

![image](https://user-images.githubusercontent.com/83296371/122974484-fcb0e900-d357-11eb-8fca-67a998cb00b0.png)

#### Steps to Reproduce
Add an mp4 to a quick view.

**Comment by dennisjsyi** [comment]
Fixed callout dismissing on video play event.
