### ISSUE TITLE
Is there workaround to call API data on Demand instead of calling it in OnInit()

### ISSUE THREAD

**Issue by vasanthkumarc94** [microsoft/Viva-Connections-Extensibility-Beta#31]
Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you.

#### Versions
[Windows 10] Operating System
[v12.22.1] Node version
[4.0.2] Gulp version
[1.13.0-beta.5] SPFx Generator version  (`npm list -g @microsoft/generator-sharepoint`)

#### Expected or Desired Behavior
****Extension.ts
Init() : method is only way where calling API data is happening. If there is necessity that where on the QuickView load we can get certain API data's there we don't have any control. Due to this I am calling several API's on card load where all API data's are necessary on the card load itself. 

if there will be control for us to load certain data on the QuickView or on the card button click it would be great feature to be add on in SPFx Viva Extension.

Scenario: If we think about the scenario's where there will be multiple Azure API call is happening on the card load it may be lead to performance issue.

**@Microsoft is there any workaround for us to avoid calling certain API's onInit, instead calling API's on QuickView load or on Card Button click**

**Comment by anoopt** [comment]
I think this is same as #16
