### ISSUE TITLE
How to use **ITextRun** interface for the Adaptive Card

### ISSUE THREAD

**Issue by vasanthkumarc94** [microsoft/Viva-Connections-Extensibility-Beta#32]
[Windows 10] Operating System
[v12.22.1] Node version
[4.0.2] Gulp version
[1.13.0-beta.5] SPFx Generator version (npm list -g @microsoft/generator-sharepoint)

#### Expected or Desired Behavior
I am trying to underline a text in Adaptive card, I found one API available for this
https://github.com/microsoft/Viva-Connections-Extensibility-Beta/wiki/sp-adaptive-card-extension-base.itextrun
ITextRun. 

Is there any sample or examples for the underline which help me to achieve the underline or other things.
Any suggestions really helpful for me... Thanking you

**Comment by vasanthkumarc94** [comment]
@johnguy0 it would be a great help If I have any examples or any document. Thank you....

**Comment by ms-nichoi** [comment]
Could you please try using ITextRun (the interface of the Adaptive Cards TextRun) in RichTextBlock?

The example in the Adaptive Cards schema explorer may help: https://adaptivecards.io/explorer/RichTextBlock.html
