### ISSUE TITLE
Quick view : TextBlock color not appearing

### ISSUE THREAD

**Issue by anoopt** [microsoft/Viva-Connections-Extensibility-Beta#33]
Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you.

#### Versions
[Ubuntu 18.04 LTS]  Operating System
[v 14.15.5]  Node version
[4.0.2]  Gulp version
[1.13.0-beta.17]  SPFx Generator version (`npm list -g @microsoft/generator-sharepoint`)

#### Expected or Desired Behavior
When `color` attribute of the `TextBlock` element is set in QuickView template json, the text should appear as per the set color detailed [here](https://adaptivecards.io/explorer/TextBlock.html)

#### Observed Behavior
The color of the text doesn't change

#### Steps to Reproduce
- Add a TextBlock in the Quickview template json
- Set the `color` attribute to any of `dark`, `light`, `attention` or `good`
- The color of the text in the quick view doesn't change

**Comment by anoopt** [comment]
One option (for now) is to use [`TextRun` element](https://adaptivecards.io/explorer/TextRun.html) if the text colour needs to be shown

![image](https://user-images.githubusercontent.com/9694225/133252923-edece772-fae8-498a-9a54-188608bf5a31.png)

**Comment by ms-nichoi** [comment]
Hi @anoopt , thanks for reporting and sharing a workaround.

The fix for this is planned to reach Prod by Monday.

**Comment by ms-nichoi** [comment]
Closing, this has been fixed.
