### ISSUE TITLE
Picker for icon/Image properties on OOB Card Designer Web Part

### ISSUE THREAD

**Issue by pkbullock** [microsoft/Viva-Connections-Extensibility-Beta#5]
#### Expected or Desired Behavior

When selecting an icon a picker or similar functionality to quick links thumbnail selection, for the Icon field in the OOB Card Designer web part.

#### Observed Behavior

These are text fields only.

![Missing Pickers](https://user-images.githubusercontent.com/8781041/116247760-13c1c900-a763-11eb-81c7-57ed3e3ac5d9.png)

#### Steps to Reproduce

Add Card Designer web part to Dashboard.

**Comment by johnguy0** [comment]
Thanks for providing this feedback during the public Beta. We'll consider this functionality in a future release.
